#!/bin/bash

# Batch Whisper Transcription Script for Udacity Courses
# Optimized for Apple Silicon

set -e

# Configuration
WHISPER_ENV="/Users/sharad/Projects/udacity-reviews-hq/whisper_env"
WHISPER_MODEL="base"  # Options: tiny, base, small, medium, large
BATCH_SIZE=4  # Number of parallel transcriptions

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

usage() {
    cat << EOF
Usage: $0 <course_directory>

Transcribes all MP4 files in a course directory using OpenAI Whisper.

Arguments:
    course_directory    Path to course context directory

Options:
    Set WHISPER_MODEL environment variable to change model (default: base)
        - tiny: Fastest, least accurate
        - base: Good balance (default)
        - small: Better accuracy, slower
        - medium: High accuracy, much slower
        - large: Best accuracy, very slow

Example:
    $0 /path/to/course/context
    WHISPER_MODEL=small $0 /path/to/course/context

EOF
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

COURSE_DIR="$1"

if [ ! -d "$COURSE_DIR" ]; then
    echo "Error: Directory not found: $COURSE_DIR"
    exit 1
fi

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}Batch Whisper Transcription${NC}"
echo -e "${BLUE}============================================${NC}"
echo -e "Course Directory: ${GREEN}$COURSE_DIR${NC}"
echo -e "Whisper Model: ${GREEN}$WHISPER_MODEL${NC}"
echo ""

# Activate virtual environment
source "$WHISPER_ENV/bin/activate"

# Find all MP4 files
MP4_FILES=$(find "$COURSE_DIR" -name "*.mp4" | sort)
TOTAL_FILES=$(echo "$MP4_FILES" | wc -l | tr -d ' ')

if [ "$TOTAL_FILES" -eq 0 ]; then
    echo "No MP4 files found in $COURSE_DIR"
    exit 0
fi

echo -e "${YELLOW}Found $TOTAL_FILES video files to transcribe${NC}"
echo ""

# Create transcripts directory
TRANSCRIPTS_DIR="$COURSE_DIR/transcripts"
mkdir -p "$TRANSCRIPTS_DIR"

# Process each video
COUNT=0
SKIPPED=0
TRANSCRIBED=0

while IFS= read -r video_file; do
    COUNT=$((COUNT + 1))

    # Get relative path for better output
    REL_PATH="${video_file#$COURSE_DIR/}"
    SECTION=$(echo "$REL_PATH" | cut -d'/' -f1)
    FILENAME=$(basename "$video_file" .mp4)

    # Create output paths
    SECTION_TRANSCRIPT_DIR="$TRANSCRIPTS_DIR/$SECTION"
    mkdir -p "$SECTION_TRANSCRIPT_DIR"

    OUTPUT_TXT="$SECTION_TRANSCRIPT_DIR/${FILENAME}.txt"
    OUTPUT_SRT="$SECTION_TRANSCRIPT_DIR/${FILENAME}.srt"

    # Skip if already transcribed
    if [ -f "$OUTPUT_TXT" ]; then
        echo -e "[${COUNT}/${TOTAL_FILES}] ${YELLOW}SKIP${NC} $REL_PATH (already transcribed)"
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    echo -e "[${COUNT}/${TOTAL_FILES}] ${BLUE}Transcribing${NC} $REL_PATH"

    # Run Whisper
    whisper "$video_file" \
        --model "$WHISPER_MODEL" \
        --language en \
        --output_dir "$SECTION_TRANSCRIPT_DIR" \
        --output_format txt \
        --output_format srt \
        --verbose False \
        --fp16 True 2>&1 | grep -v "Downloading" || true

    TRANSCRIBED=$((TRANSCRIBED + 1))

    echo -e "[${COUNT}/${TOTAL_FILES}] ${GREEN}DONE${NC} $REL_PATH"
    echo ""

done <<< "$MP4_FILES"

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}Transcription Complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo -e "Total files: ${TOTAL_FILES}"
echo -e "Transcribed: ${GREEN}${TRANSCRIBED}${NC}"
echo -e "Skipped: ${YELLOW}${SKIPPED}${NC}"
echo -e "Output directory: ${BLUE}$TRANSCRIPTS_DIR${NC}"
echo ""

# Generate master transcript
echo -e "${BLUE}Generating master transcript...${NC}"

MASTER_TRANSCRIPT="$COURSE_DIR/MASTER_TRANSCRIPT_WHISPER.txt"

cat > "$MASTER_TRANSCRIPT" << HEADER
================================================================================
MASTER TRANSCRIPT (Generated by Whisper AI)
Course: $(basename "$(dirname "$COURSE_DIR")")
Model: $WHISPER_MODEL
Generated: $(date '+%Y-%m-%d %H:%M:%S')
Total Videos: $TOTAL_FILES
================================================================================

HEADER

# Append all transcripts
find "$TRANSCRIPTS_DIR" -name "*.txt" | sort | while read -r transcript; do
    REL_PATH="${transcript#$TRANSCRIPTS_DIR/}"
    SECTION=$(dirname "$REL_PATH")
    FILENAME=$(basename "$transcript" .txt)

    cat >> "$MASTER_TRANSCRIPT" << SECTION_HEADER

################################################################################
# Section: $SECTION
# File: $FILENAME
################################################################################

SECTION_HEADER

    cat "$transcript" >> "$MASTER_TRANSCRIPT"
    echo "" >> "$MASTER_TRANSCRIPT"
done

MASTER_SIZE=$(du -h "$MASTER_TRANSCRIPT" | cut -f1)
echo -e "${GREEN}Master transcript created:${NC} $MASTER_TRANSCRIPT ($MASTER_SIZE)"
echo ""
echo -e "${GREEN}All done!${NC}"
